services:
  ssh-log-web:
    image: "ssh-log-web:0.1"
    restart: unless-stopped
    volumes:
      - "/var/log/journal:/www/log/journal:ro" # 日志目录
    environment:
      - TZ=Asia/Shanghai
      - API=http://localhost:43000 # 后端的api地址，默认为localhost:43000，请调整为自己服务器的ip地址和自己想要的端口
    network_mode: "host"
    container_name: ssh-log-web
    hostname: ssh-log-web
